### ISSUE TITLE
key exposed in .env

### ISSUE THREAD

**Issue by boltomli** [lazerwalker/neural-tts-sample#1]
It seems you'd keep that as a secret.

**Comment by lazerwalker** [comment]
Yep, thanks for mentioning! I'm already in the process of working through a deployment strategy that lets us keep this as a secret while still using Azure Static Apps for deployment, and the plan has been to cycle this specific compromised key before the accompanying blog post/etc about this sample project get published.

**Comment by lazerwalker** [comment]
This is now properly storing all secrets in GitHub Secrets, and that specific key has been cycled 👍
